version: "3.9"
services:

  database:
    container_name: postgres_container
    image: postgres:16.3-alpine3.19
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - kill-list-db-data:/var/lib/postgresql/data
    ports:
      - "5432:${POSTGRES_PORT}"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_conatiner
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "habrpguser@habr.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4habr"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on:
      - database
    
  backend:
    container_name: backend_container
#    image: golang:1.19
    build: ./
    command: /server
    ports:
      - "8000:8000"
    depends_on:
      - database
  # frontend:

volumes:
  kill-list-db-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
